### ISSUE TITLE
buy signals shouldn't occur inside of trades for same pair

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade-strategies#310] opened 2024-06-04 13:08 UTC
## Describe your environment

  * Operating system: Linux____
  * Python Version: _3____ (`python -V`)
  * CCXT version: __4.3.11___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2024.4__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Strategy: __BreakEven___
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

FreqTrade supports maximum 1 open trade per pair.
During backtesting, when a buy trade executes, why does FreqTrade allows multiple Entry signals to appear since a sell didn't occur yet?
Is this a bug?

### Steps to reproduce:

  1. In a strategy, add a simple condition that triggers multiple buy signals on several candles before a sell occurs
  2. The first buy signal will trigger a buy order to be executed
  3. The following candles will have Entry signals even before the matching sell gets executed 

  
### Observed Results:

There are multiple Entry signals within an active trade. This shouldn't be normal since FreqTrade allows only 1 open trade because none of the following Entry signals can get executed before the order gets sold(trade closes)

**Comment by xmatthias** [comment] 2024-06-04 15:01
You need to differentiate between buy **signals** - and actual buys.
A signal happens whenever you have `enter_long = 1` in your strategy.
An actual buy is when that signal is acted on (an order is created). 

There will only one signal that will be acted on (the first). 
Subsequent signals will still be signals (that's what you assign to the dataframe after all) - but that doesn't mean that they're acted on - hence they'll not be creating actual orders.

They'll ONLY be acted on  when providing additional an additional flags to backtesting  (also called the "unrealistic" mode) - otherwise, they'll not be acted on.

**Comment by uplight-dev** [comment] 2024-06-04 18:28
Thanks but is it not a bug to see hundreds of buy signals in the "realistic" mode? Why not hide them unless in "unrealistic" mode?

**Comment by stash86** [comment] 2024-06-05 02:09
They are there to show you candles where your entry signals are triggered. Same thing on exit signal.

It is useful for plenty of reasons, for example if you want to know how good is the entry logic. Is is too loose or too tight? Are the bad entry signals? And so on.

**Comment by stash86** [comment] 2024-06-05 02:11
> Thanks but is it not a bug to see hundreds of buy signals in the "realistic" mode? Why not hide them unless in "unrealistic" mode?

Then you have (seems like very) loose entry signals if you have multiple consecutive entry signals. It's not a bug on freqtrade, but (in my personal opinion) can be considered a "bug" of your strategy.

**Comment by xmatthias** [comment] 2024-06-05 04:22
> Thanks but is it not a bug to see hundreds of buy signals in the "realistic" mode?

No, it's intentional and desired behavior this way.

---

As another argument - there's mulitple factors that play into the fact if a signal is acted on besides "is a trade for this pair open".
This can range from "no capital available" - to "no trade-slot available" - to "protection locked this pair until X" - or even "the bot was started in the middle of 20 consecutive signals".
If we were to hide all but the first signal - you'd have a "ghost" entry - which enters while not showing a signal.

Showing all signals can also show you "this would also  have entered later" - or "it's still a good signal that would still be entered on".

As an aside, it can also have impacts on open trades (there's a setting to not take ROI if the entry signal is still active).


---

As @stash86  also mentions - if this is not how you'd like to see things - then your strategy should adapt. Freqtrade / FreqUI will just show you what the strategy says.
A "sticking" signal is often a lose comparison (rsi < 30) ... while in reality, you'll often want to enter when RSI crosses 30 from top (or bottom) - so by showing all signals, you've been shown a non-desired behavior in your strategy.

**Closed by xmatthias** 2024-06-05 04:22 UTC
Labels: question
