### ISSUE TITLE
Calculation from your buy point(price)?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade-strategies#99] opened 2020-09-21 14:11 UTC
*For requestion a new strategy. Please use the template below.*  
*Any strategy request that does not follow the template will be closed.*

## Step 1: What indicators are required?
ATR-AVERAGE TRUE RANGE

## Step 1: Explain the Sell Strategy
I want to sell it when the price dropped 1 ATR from my last buy price.?
 I know  stop_loss & ROI function calculation is based on our last buy, but how can I define it and use this value for further calculations?
I deeply appreciate your time & effort in sharing your valuable time & knowledge.

**Comment by xmatthias** [comment] 2020-09-23 18:04
I'll close this as duplicate of https://github.com/freqtrade/freqtrade/issues/3800.

**Closed by xmatthias** 2020-09-23 18:04 UTC
