### ISSUE TITLE
AverageHyperopt Issue

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade-strategies#104] opened 2020-10-18 13:26 UTC
## Describe your environment

  * Operating system: Ubunti 18.04
  * Python Version: Python 3.7.4
  * CCXT version: ccxt==1.36.12
  * Freqtrade Version: freqtrade develop-8ae193f6

## Describe the problem:

I have just tried to apply the AverageHyperopt file, see error msg below

I used following CLI cmd:

`freqtrade hyperopt -c config_binance_BTC1.json --strategy AverageStrategy_BTC_RSI_1h --hyperopt AverageHyperopt -e 1000 --spaces all --hyperopt-loss SharpeHyperOptLossDaily --timerange=20190501-20201014  --ticker-interval 1h`

```
2020-10-18 15:19:05,418 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2020-10-18 15:19:05,419 - freqtrade.optimize.hyperopt_interface - INFO - Min roi table: {0: 0.06883, 120: 0.04589, 240: 0.02294, 360: 0}
2020-10-18 15:19:05,419 - freqtrade.optimize.hyperopt_interface - INFO - Max roi table: {0: 0.71124, 480: 0.25238, 1200: 0.09177, 2640: 0}
2020-10-18 15:19:05,439 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 12
+--------+-----------+----------+------------------+--------------+------------------------------+----------------+-------------+
|   Best |     Epoch |   Trades |    Win Draw Loss |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+-----------+----------+------------------+--------------+------------------------------+----------------+-------------|
| * Best |    1/1000 |     2927 |    928  415 1584 |       -0.38% | -0.16906241 BTC (-1,125.96%) |      1,374.7 m |     2.44997 |
| * Best |    7/1000 |     3140 |   1055  566 1519 |       -0.26% |   -0.12181582 BTC (-811.29%) |      1,403.1 m |     1.81025 |                                                                                 
| * Best |   12/1000 |     3127 |    991  517 1619 |        0.04% |    0.01668845 BTC  (111.15%) |      1,364.5 m |      0.0786 |
 [Epoch 13 of 1000 (  1%)] |█-                                                                                                                                           | [ETA:   0:36:44, Elapsed Time: 0:00:29]
| * Best |   14/1000 |     3118 |   1064  400 1654 |        0.26% |    0.12243940 BTC  (815.44%) |      1,293.9 m |    -1.06333 |
2020-10-18 15:20:09,120 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/hyperopt.py", line 713, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/optimizer/optimizer.py", line 447, in _ask
    for xi in self.Xi])
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/optimizer/optimizer.py", line 447, in <listcomp>
    for xi in self.Xi])
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/space/space.py", line 1132, in distance
    distance += dim.distance(a, b)
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/space/space.py", line 737, in distance
    if not (a in self and b in self):
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/skopt/space/space.py", line 714, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Whats the issue here?

**Comment by xmatthias** [comment] 2020-10-18 14:09
This is technically a duplicate of https://github.com/freqtrade/freqtrade/issues/3796.

In short - it seems to be caused by an update to scikit-optimize - which now doesn't seem to support tuples as category values.
You can work around by using strings and then splitting the strings again as shown in the issue.


Best read the comments (especially the last few) to work around this issue.

**Closed** 2020-10-18 15:48 UTC
Labels: duplicate
