### ISSUE TITLE
'No module named 'ta''

### ISSUE THREAD

**Issue by khannzxc** [freqtrade/freqtrade-strategies#199] opened 2021-06-08 07:48 UTC
freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/GodStra.py due to 'No module named 'ta''.

I have installed pip install ta but the strategy is still giving the above error and bit keeps on restarting
using docker-compose ps -a.
How can this be fixed?

**Comment by xmatthias** [comment] 2021-06-08 16:56
duplicate of #171 ...

you'll need to add the dependency in docker to use this corerctly [as documented here](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose).

**Closed by xmatthias** 2021-06-08 16:56 UTC
Labels: duplicate, question
